### ISSUE TITLE
I broke Box#destroy

### ISSUE THREAD

**Issue by rtyler** [rtyler/blimpy#4]
Note to self

```
fail
```

**Comment by rtyler** [comment]
```

-> % ./bin/blimpy destroy
/home/tyler/source/github/gems/blimpy/lib/blimpy/fleet.rb:63:in `block in destroy': undefined method `destroy' for nil:NilClass (NoMethodError)
        from /home/tyler/source/github/gems/blimpy/lib/blimpy/fleet.rb:61:in `each'
        from /home/tyler/source/github/gems/blimpy/lib/blimpy/fleet.rb:61:in `destroy'
        from ./bin/blimpy:63:in `destroy'
        from /home/tyler/.rvm/gems/ruby-1.9.2-p290@blimpy/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
        from /home/tyler/.rvm/gems/ruby-1.9.2-p290@blimpy/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from /home/tyler/.rvm/gems/ruby-1.9.2-p290@blimpy/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
        from /home/tyler/.rvm/gems/ruby-1.9.2-p290@blimpy/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
        from ./bin/blimpy:86:in `<main>'
```

**Comment by rtyler** [comment]
Starting work on this now.

(_This message brought to you by [Hub board](http://hubboard.herokuapp.com/about)_)
