### ISSUE TITLE
blimpy start fails on fog 1.9.0

### ISSUE THREAD

**Issue by rtyler** [rtyler/blimpy#85]
```
[9:16:40] tyler:puppet-jenkins git:(next*) $ blimpy start
[excon][WARNING] Invalid Excon request keys: :host
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/excon-0.31.0/lib/excon/connection.rb:389:in `validate_params'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/excon-0.31.0/lib/excon/connection.rb:225:in `request'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/fog-1.9.0/lib/fog/core/connection.rb:21:in `request'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/fog-1.9.0/lib/fog/aws/compute.rb:384:in `_request'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/fog-1.9.0/lib/fog/aws/compute.rb:379:in `request'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/fog-1.9.0/lib/fog/aws/requests/compute/describe_security_groups.rb:43:in `describe_security_groups'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/fog-1.9.0/lib/fog/aws/models/compute/security_groups.rb:66:in `all'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/fog-1.9.0/lib/fog/aws/models/compute/security_groups.rb:90:in `get'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/blimpy-0.6.7/lib/blimpy/boxes/aws.rb:33:in `validate!'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/blimpy-0.6.7/lib/blimpy/fleet.rb:110:in `block in start'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/blimpy-0.6.7/lib/blimpy/fleet.rb:109:in `each'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/blimpy-0.6.7/lib/blimpy/fleet.rb:109:in `start'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/blimpy-0.6.7/lib/blimpy/cli.rb:74:in `start'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/gems/blimpy-0.6.7/bin/blimpy:20:in `<top (required)>'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/bin/blimpy:19:in `load'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/bin/blimpy:19:in `<main>'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/bin/ruby_executable_hooks:15:in `eval'
/home/tyler/.rvm/gems/ruby-1.9.3-p484@rubygems/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rtyler** [comment]
Looks like fog 1.20 works fine, might need to make the gemspec more specific
